In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv('/content/train.csv')

In [3]:
df.head()

id  qid1  qid2                                          question1  \
0   0     1     2  What is the step by step guide to invest in sh...   
1   1     3     4  What is the story of Kohinoor (Koh-i-Noor) Dia...   
2   2     5     6  How can I increase the speed of my internet co...   
3   3     7     8  Why am I mentally very lonely? How can I solve...   
4   4     9    10  Which one dissolve in water quikly sugar, salt...   

                                           question2  is_duplicate  
0  What is the step by step guide to invest in sh...             0  
1  What would happen if the Indian government sto...             0  
2  How can Internet speed be increased by hacking...             0  
3  Find the remainder when [math]23^{24}[/math] i...             0  
4            Which fish would survive in salt water?             0

In [4]:
df= df.dropna()
df= df.sample(30000)

In [5]:
new_df= df[['question1','question2']]

In [6]:
new_df.shape

(30000, 2)

In [7]:
questions= list(new_df['question1'])+list(new_df['question2'])

In [8]:
from sklearn.feature_extraction.text import CountVectorizer  #array is used in countvectorizer
cv= CountVectorizer(max_features=3000)

In [9]:
qarry1,qarry2= np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
print(qarry1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
temp_df1= pd.DataFrame(qarry1,index=new_df.index)
temp_df2= pd.DataFrame(qarry2,index=new_df.index)
temp_df= pd.concat([temp_df1,temp_df2],axis=1)
temp_df.shape

(30000, 6000)

In [12]:
temp_df['is_duplicate']= df['is_duplicate']

In [13]:
temp_df.head()

0  1  2  3  4  5  6  7  8  9  ...  2991  2992  2993  2994  2995  2996  \
273506  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
297063  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
402473  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
149445  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
150700  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

        2997  2998  2999  is_duplicate  
273506     0     0     0             1  
297063     0     0     0             1  
402473     0     0     0             0  
149445     0     0     0             1  
150700     0     0     0             0  

[5 rows x 6001 columns]

In [14]:
x= temp_df.iloc[:,0:-1]
y= temp_df.iloc[:,-1]

In [15]:
print(x.sample(10))

        0     1     2     3     4     5     6     7     8     9     ...  2990  \
31747      0     0     0     0     0     0     0     0     0     0  ...     0   
351759     0     0     0     0     0     0     0     0     0     0  ...     0   
287140     0     0     0     0     0     0     0     0     0     0  ...     0   
201331     0     0     0     0     0     0     0     0     0     0  ...     0   
5931       0     0     0     0     0     0     0     0     0     0  ...     0   
188937     0     0     0     0     0     0     0     0     0     0  ...     0   
327211     0     0     0     0     0     0     0     0     0     0  ...     0   
281952     0     0     0     0     0     0     0     0     0     0  ...     0   
76607      0     0     0     0     0     0     0     0     0     0  ...     0   
311076     0     0     0     0     0     0     0     0     0     0  ...     0   

        2991  2992  2993  2994  2995  2996  2997  2998  2999  
31747      0     0     0     0     0     0   

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)

In [17]:
x_train.shape

(24000, 6000)

In [18]:
!pip install xgboost

In [19]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
rf= RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print('accuracy_score= ',accuracy_score(y_pred,y_test))

accuracy_score=  0.7435


In [22]:
x_train

0     1     2     3     4     5     6     7     8     9     ...  2990  \
196551     0     0     0     0     0     0     0     0     0     0  ...     0   
305809     0     0     0     0     0     0     0     0     0     0  ...     0   
65461      0     0     0     0     0     0     0     0     0     0  ...     0   
20047      0     0     0     0     0     0     0     0     0     0  ...     0   
324902     0     0     0     0     0     0     0     0     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
89567      0     0     0     0     0     0     0     0     0     0  ...     0   
62975      0     0     0     0     0     0     0     0     0     0  ...     0   
129455     0     0     0     0     0     0     0     0     0     0  ...     0   
165681     0     0     0     0     0     0     0     0     0     0  ...     1   
350643     0     0     0     0     0     0     0     0     0     0  ...     0   

        2991  2992  2993  2994  2995  2996  2997  2998  2999  
196551     0     0     0     1     0     0     0     0     0  
305809     0     0     0     0     0     0     0     0     0  
65461      0     0     0     0     0     0     0     0     0  
20047      0     0     0     0     0     0     0     0     0  
324902     0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
89567      0     0     0     0     0     0     0     0     0  
62975      0     0     0     0     0     0     0     0     0  
129455     0     0     0     0     0     0     0     0     0  
165681     0     0     0     0     0     0     0     0     0  
350643     0     0     0     0     0     0     0     0     0  

[24000 rows x 6000 columns]

In [30]:
xgb= XGBClassifier()
xgb.fit(x_train.values,y_train)
y_pred= xgb.predict(x_test.values)
print(accuracy_score(y_pred,y_test))

0.7293333333333333
